apiVersion: apps/v1
kind: Deployment
metadata:
  name: pqc-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pqc-test-app
  template:
    metadata:
      labels:
        app: pqc-test-app
    spec:
      containers:
      - name: pqc-test-app
        image: <your-registry>/pqc-test-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pqc-test-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: pqc-test-app
